namespace :test do
  desc "Run all tests"
  task :all => [:spec,:acceptance]

  desc "Run acceptance tests"
  task :acceptance do
    sh "rspec test/acceptance/*.rb"
  end

  desc "Run specs"
  task :spec do
    sh "rspec test/spec/*.rb"
  end
end
