source "http://www.rubygems.org"

gem 'activerecord', "3.2.13"
gem 'activesupport', '3.2.13'
gem 'rake', '0.9.2.2'
gem 'sqlite3', '1.3.7'
gem 'rspec', '2.13.0'
gem 'rr', '1.0.5'
gem 'activerecord-nulldb-adapter'
